# Generated by Django 6.0.3 on 2026-04-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('folder_path', models.TextField()),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dir', models.TextField()),
            ],
            options={
                'db_table': 'lang',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('ip', models.CharField(default='1', max_length=50, primary_key=True, serialize=False)),
                ('view', models.BigIntegerField(default=1)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('lang', models.CharField(default='en', max_length=5)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('plays', models.IntegerField(default=0)),
                ('dir', models.TextField()),
                ('lang', models.ForeignKey(blank=True, db_column='lang', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.lang')),
            ],
            options={
                'db_table': 'file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plays', models.IntegerField(default=0)),
                ('mp3', models.TextField()),
                ('album', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='api.album')),
                ('lang', models.ForeignKey(blank=True, db_column='lang', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.lang')),
            ],
            options={
                'db_table': 'track',
            },
        ),
    ]
