upstream zaideih {
    server web:8000;
}

server {
    listen 80;

    # Django Dynamic Content
    location / {
        proxy_pass http://zaideih;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Static Files (CSS, JS, Favicon)
    location /static/ {
        alias /code/static_root/;
    }

    # Media/Cache Files (Your .mp3 files)
    location /cache/ {
        alias /code/cache/;
    }
}