server {
    listen 80;

    # 1. Route API and Admin to Django (Gunicorn/Runserver)
    location ~ ^/(api|admin) {
        proxy_pass http://web:${APP_PORT};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Route everything else to the Vite Dev Server
    location / {
        proxy_pass http://vite:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}