name: Bulk Delete Containers

on:
  workflow_dispatch: # Allows you to trigger it manually from the UI

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      # This runs the steps for both packages in parallel
      matrix:
        package: ['nginx-prod', 'django-app']
    steps:
      - name: Delete old versions for ${{ matrix.package }}
        uses: actions/delete-package-versions@v5
        with:
          owner: 'khensolomon'
          package-name: ${{ matrix.package }}
          package-type: 'container'
          min-versions-to-keep: 5 # Keeps the 5 newest versions, deletes the other 495+
          # To delete ONLY untagged/broken images, uncomment the line below:
          # delete-only-untagged-versions: true 
          token: ${{ secrets.DELETE_PACKAGES_TOKEN }}